name = "Indexes"
uuid = "4ffb77ac-cb80-11e8-1b35-4b78cc642f6d"
authors = ["Kenta Sato <bicycle1885@gmail.com>", "Ben J. Ward <benjward@protonmail.com>", "Ciarán O’Mara <CiaranOMara@utas.edu.au>"]
version = "0.1.3"

[deps]
BGZFStreams = "28d598bf-9b8f-59f1-b38c-5a06b4a0f5e6"
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
GenomicFeatures = "899a7d2d-5c61-547b-bef9-6698a8d05446"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
BGZFStreams = "0.3"
BioGenerics = "0.1"
GenomicFeatures = "2"
TranscodingStreams = "0.9.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
